#!/bin/bash

# grab solarized install scripts

cd ~
git clone https://github.com/payneio/gnome-terminal-colors-solarized.git
cd gnome-terminal-colors-solarized
./set_dark.sh
cd ~
rm -Rf gnome-terminal-colors-solarized

